export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  VENDOR_NOT_FOUND: "VENDOR_NOT_FOUND",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  PLAN_NOT_STARTED_REQUIRED: "PLAN_NOT_STARTED_REQUIRED",
  PLAN_ASSIGNED_VENDOR_REQUIRED: "PLAN_ASSIGNED_VENDOR_REQUIRED",
  VENDOR_NOT_SUSPENDED: "VENDOR_NOT_SUSPENDED",
  VENDOR_ALREADY_SUSPENDED: "VENDOR_ALREADY_SUSPENDED",
  TARGET_VENDOR_INACTIVE: "TARGET_VENDOR_INACTIVE",
  SERVICE_SCOPE_MISMATCH: "SERVICE_SCOPE_MISMATCH",
  ELIGIBLE_VENDOR_EXISTS: "ELIGIBLE_VENDOR_EXISTS",
  NO_ELIGIBLE_VENDOR: "NO_ELIGIBLE_VENDOR",
  PLAN_VERSION_CONFLICT: "PLAN_VERSION_CONFLICT",
  PLAN_ALREADY_HANDLED: "PLAN_ALREADY_HANDLED",
  REASON_REQUIRED: "REASON_REQUIRED",
  HANDLER_REQUIRED: "HANDLER_REQUIRED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
