export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_FOUND: "NOT_FOUND",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  VENDOR_NOT_FOUND: "VENDOR_NOT_FOUND",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  VENDOR_NOT_SUSPENDED: "VENDOR_NOT_SUSPENDED",
  VENDOR_SUSPENDED: "VENDOR_SUSPENDED",
  VENDOR_SCOPE_MISMATCH: "VENDOR_SCOPE_MISMATCH",
  PLAN_NOT_UNSTARTED: "PLAN_NOT_UNSTARTED",
  PLAN_VERSION_CONFLICT: "PLAN_VERSION_CONFLICT",
  BLOCKED_REASON_REQUIRED: "BLOCKED_REASON_REQUIRED",
  REASSIGN_REASON_REQUIRED: "REASSIGN_REASON_REQUIRED"
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
